### ISSUE TITLE
Fresh install of an already working donejs project won't work (ReferenceError: Node is not defined)

### ISSUE THREAD

**Issue by nriesco** [donejs/donejs#1009]
__How often can you reproduce it?__ 

- [ ] Always
- [x] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

We have a currently working project that was generated using `donejs@1` about 3 months ago. Everything was ok but we tried to install the project in a new computer and the project just won't start. We tried almost everything even reducing the project to the minimum possible.

The error is `ReferenceError: Node is not defined` shown both in the browser and the console.

__Steps to reproduce:__

1. Consider a project that ok
2. run `npm install` and the project still runs
3. Create a new version of the project on the same computer and do a fresh install and it won't start
4. The same project, reduce it to the minimum (see below) and it won't start either
5. Any new computers (Computer-2 and so on..) won't be able to start the project

Use: `donejs develop` to run the project.

__Expected results:__

It should show a `hello world!` text when loading [http://localhost:8080/](http://localhost:8080/)

__Actual results:__

Shows an error:

```
ReferenceError: Node is not defined
    at isDomEventTarget (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-dom-events/helpers/util.js:40:22)
    at addDomContext (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-dom-events/helpers/util.js:44:6)
    at InputElement.addEventListener (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-dom-events/helpers/add-event-compat.js:66:15)
    at InputElement.addEventListener (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-dom-events/helpers/add-event-compat.js:69:30)
    at InputElement.on (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-event/can-event.js:195:28)
    at event (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-stache-bindings/can-stache-bindings.js:526:16)
    at InputElement.<anonymous> (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-stache/can-stache.js:304:7)
    at hydrateCallbacks (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-view-target/can-view-target.js:256:39)
    at Object.hydrate (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-view-target/can-view-target.js:275:4)
    at rendererWithScope (file:/Users/nriesco/git/temp/ozzi-application/node_modules/can-stache/src/utils.js:56:11)
```

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 1.0.0
| node -v                  | v6.11.2
| npm -v                   | 3.10.10
| Browser                 | Chrome - Version 59.0.3071.115 (Official Build) (64-bit)
| Operating system | Darwin Gris.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

__Minimum Project:__

index.stache

```
<html>
<head>
  <title>hello</title>
</head>
<body>
  hello world!

  {{#switch env.NODE_ENV}}
    {{#case "production"}}
      <script src="{{joinBase 'steal.production.js'}}"></script>
    {{/case}}
    {{#default}}
      <script src="/node_modules/steal/steal.js"></script>
    {{/default}}
  {{/switch}}
</body>
</html>
```

app.js

```
import DefineMap from 'can-define/map/';
const AppViewModel = DefineMap.extend({});
export default AppViewModel;
```

dependencies:

```
"dependencies": {
    "can-component": "^3.0.7",
    "can-connect": "^1.3.10",
    "can-connect-feathers": "^2.0.0",
    "can-define": "^1.0.17",
    "can-route": "^3.0.10",
    "can-route-pushstate": "^3.0.3",
    "can-set": "^1.2.0",
    "can-stache": "^3.0.20",
    "can-view-autorender": "^3.0.4",
    "can-zone": "^0.6.6",
    "done-autorender": "^1.0.0",
    "done-component": "^1.0.0",
    "done-css": "^3.0.0",
    "done-serve": "^1.0.0",
    "generator-donejs": "^1.0.0",
    "steal": "^1.5.4",
    "steal-less": "^1.2.0",
    "steal-platform": "0.0.4",
    "steal-stache": "^3.0.5",
    "testee": "^0.4.0"
  },
```

**Comment by matthewp** [comment]
Thanks, will take a look at this right away.

**Comment by matthewp** [comment]
Doesn't fail on a fresh `donejs add app`, could be a dep you are using. Going to try again with your deps.

**Comment by matthewp** [comment]
@nriesco can you post your devDependencies as well?

**Comment by nriesco** [comment]
@matthewp 

```
"devDependencies": {
    "can-fixture": "^1.0.13",
    "donejs-cli": "^1.0.0",
    "firebase-tools": "^3.9.0",
    "funcunit": "^3.2.0",
    "steal-qunit": "^1.0.1",
    "steal-tools": "^1.2.0",
    "testee": "^0.3.0"
  }
```

**Comment by matthewp** [comment]
@nriesco looks like your pasting got cut off?

**Comment by nriesco** [comment]
This is the whole package.json file:
```
{
  "name": "my app",
  "version": "0.0.0",
  "description": "An awesome DoneJS app",
  "homepage": "",
  "repository": {
    "type": "git",
  },
  "author": {
    "name": "",
    "email": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "test": "testee test.html --browsers firefox --reporter Spec",
    "start": "done-serve --port 8080",
    "testing": "NODE_ENV=testing done-serve --develop --port 8080",
    "develop": "done-serve --develop --port 8080",
    "develop:proxy": "done-serve --develop --proxy http://localhost:3030 --port 8080",
    "develop:static": "done-serve --static --port 8080",
    "document": "./node_modules/.bin/documentjs",
    "document:develop": "./node_modules/.bin/documentjs --watch",
    "build": "node build",
    "deploy": "firebase deploy",
    "deploy:ci": "firebase deploy --token \"$FIREBASE_TOKEN\""
  },
  "main": "ozzi-application/index.stache!done-autorender",
  "files": [
    "src"
  ],
  "keywords": [],
  "steal": {
    "main": "ozzi-application/index.stache!done-autorender",
    "directories": {
      "lib": "src"
    },
    "configDependencies": [
      "live-reload",
      "node_modules/can-zone/register"
    ],
    "plugins": [
      "done-css",
      "done-component",
      "steal-less",
      "steal-stache"
    ],
    "envs": {
      "server-production": {
        "renderingBaseURL": ""
      }
    },
    "serviceBaseURL": "",
    "urlApi": "http://localhost:3030"
  },
  "dependencies": {
    "bootstrap": "^3.3.7",
    "bootstrap-datepicker": "^1.6.4",
    "can-component": "^3.0.7",
    "can-connect": "^1.3.10",
    "can-connect-feathers": "^2.0.0",
    "can-define": "^1.0.17",
    "can-route": "^3.0.10",
    "can-route-pushstate": "^3.0.3",
    "can-set": "^1.2.0",
    "can-stache": "^3.0.20",
    "can-view-autorender": "^3.0.4",
    "can-zone": "^0.6.6",
    "documentjs": "^0.5.0",
    "done-autorender": "^1.0.0",
    "done-component": "^1.0.0",
    "done-css": "^3.0.0",
    "done-serve": "^1.0.0",
    "font-awesome": "^4.7.0",
    "generator-donejs": "^1.0.0",
    "steal": "^1.5.4",
    "steal-less": "^1.2.0",
    "steal-platform": "0.0.4",
    "steal-stache": "^3.0.5",
    "testee": "^0.4.0"
  },
  "devDependencies": {
    "can-fixture": "^1.0.13",
    "donejs-cli": "^1.0.0",
    "firebase-tools": "^3.9.0",
    "funcunit": "^3.2.0",
    "steal-qunit": "^1.0.1",
    "steal-tools": "^1.2.0",
    "testee": "^0.3.0"
  }
}
```

**Comment by matthewp** [comment]
Hey @nriesco, so first thing is that the stache template is missing a viewModel export. You want to add:

```handlebars
<can-import from="~/app" export-as="viewModel"/>
```

Were you missing this in your app?  I got a different error than you, so I suspect not.

**Comment by nriesco** [comment]
@matthewp that line (or equivalent one) was in the original project and at some point when I started removing stuff I deleted it.

The strange thing is that when I added it to the very simple project that fixed the error (good, that's a starting point) but the problem is that after removing it again I got a different error (reasonable error, see below).

So
1. project working
2. new install won't work
3. remove stuff won't work
4. add this one line again and started working
5. remove this line and get a different error
6. add the line and it works

I'll try again starting from the full project and see if I can replicate the error or fix it in the way of removing stuff.
```
TypeError: render is not a function
    at /Users/nriesco/git/temp/dos/ozzi-application/node_modules/done-ssr/lib/strategies/safe.js:102:4
    at Task.run (/Users/nriesco/git/temp/dos/ozzi-application/node_modules/can-zone/lib/zone.js:37:17)
    at Zone.run (/Users/nriesco/git/temp/dos/ozzi-application/node_modules/can-zone/lib/zone.js:197:26)
    at /Users/nriesco/git/temp/dos/ozzi-application/node_modules/done-ssr/lib/strategies/safe.js:101:15
    at tryCatchReject (/Users/nriesco/git/temp/dos/ozzi-application/node_modules/steal/src/loader/loader.js:1183:30)
    at runContinuation1 (/Users/nriesco/git/temp/dos/ozzi-application/node_modules/steal/src/loader/loader.js:1142:4)
    at Fulfilled.when (/Users/nriesco/git/temp/dos/ozzi-application/node_modules/steal/src/loader/loader.js:930:4)
    at Pending.run (/Users/nriesco/git/temp/dos/ozzi-application/node_modules/steal/src/loader/loader.js:821:13)
    at Scheduler._drain (/Users/nriesco/git/temp/dos/ozzi-application/node_modules/steal/src/loader/loader.js:97:19)
    at Scheduler.drain (/Users/nriesco/git/temp/dos/ozzi-application/node_modules/steal/src/loader/loader.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
```

**Comment by nriesco** [comment]
On another project, I had an error that was presumably related to npm's cache. It might be related to what happened here. I'll keep trying to replicate/fix the error.

**Comment by nriesco** [comment]
On the new clean install that has the error ('ReferenceError: Node is not defined') I ran `npm list --depth=0` and got this:

```
npm ERR! peer dep missing: jquery@>=1.9.0 <3.0.0, required by can@2.3.8
npm ERR! extraneous: can@2.3.8 /Users/nriesco/git/temp/ozzi-application/node_modules/can
npm ERR! extraneous: cssify@0.6.0 /Users/nriesco/git/temp/ozzi-application/node_modules/cssify
npm ERR! extraneous: engine-dependencies@0.2.11 /Users/nriesco/git/temp/ozzi-application/node_modules/engine-dependencies
npm ERR! extraneous: randomstring@1.1.5 /Users/nriesco/git/temp/ozzi-application/node_modules/randomstring
npm ERR! extraneous: steal-systemjs@0.16.6-bitovi.13 /Users/nriesco/git/temp/ozzi-application/node_modules/steal-systemjs
npm ERR! extraneous: system-json@0.0.3 /Users/nriesco/git/temp/ozzi-application/node_modules/system-json
npm ERR! invalid: testee@0.4.1 /Users/nriesco/git/temp/ozzi-application/node_modules/testee
```

**Comment by nriesco** [comment]
This is the most basic failing project I could create
[fail1.zip](https://github.com/donejs/donejs/files/1219535/fail1.zip)

The combination of importing (not even using) a component and an input with a binding to the enter event will trigger the error. If you comment any of those it will work. 

index.stache
```
<html>
<head><title>fail 1</title></head>

<body>
  <can-import from="~/app" export-as="viewModel" />
  <can-import from="~/fail.component" />

  <input ($enter)="fail()">  

  {{#switch env.NODE_ENV}}
    {{#case "production"}}
      <script src=" {{joinBase 'steal.production.js'}} "></script>
    {{/case}}
    {{#default}}
      <script src="/node_modules/steal/steal.js "></script>
    {{/default}}
  {{/switch}}
</body>
</html>
```

fail.component
```
<can-component tag="include-me-to-fail">
  <template>fail</template>
</can-component>
```

app.js
```
import DefineMap from 'can-define/map/';
import 'can-route-pushstate';

const AppViewModel = DefineMap.extend({
  fail: function() { console.log('hello!'); },
});

export default AppViewModel;
```

package.json
```
{
  "name": "my-app",
  "version": "0.0.0",
  "description": "An awesome DoneJS app",
  "homepage": "",
  "repository": {
    "type": "git"
  },
  "author": {
    "name": "",
    "email": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "test": "testee test.html --browsers firefox --reporter Spec",
    "start": "done-serve --port 8080",
    "testing": "NODE_ENV=testing done-serve --develop --port 8080",
    "develop": "done-serve --develop --port 8080",
    "develop:proxy": "done-serve --develop --proxy http://localhost:3030 --port 8080",
    "develop:static": "done-serve --static --port 8080",
    "document": "./node_modules/.bin/documentjs",
    "document:develop": "./node_modules/.bin/documentjs --watch",
    "build": "node build",
    "deploy": "firebase deploy",
    "deploy:ci": "firebase deploy --token \"$FIREBASE_TOKEN\""
  },
  "main": "my-app/index.stache!done-autorender",
  "files": [
    "src"
  ],
  "keywords": [],
  "steal": {
    "main": "my-app/index.stache!done-autorender",
    "directories": {
      "lib": "src"
    },
    "configDependencies": [
      "live-reload",
      "node_modules/can-zone/register"
    ],
    "plugins": [
      "done-css",
      "done-component",
      "steal-less",
      "steal-stache"
    ],
    "envs": {
      "server-production": {
        "renderingBaseURL": ""
      }
    },
    "serviceBaseURL": "",
    "urlApi": "http://localhost:3030"
  },
  "dependencies": {
    "bootstrap": "^3.3.7",
    "bootstrap-datepicker": "^1.6.4",
    "can-component": "^3.0.7",
    "can-connect": "^1.3.10",
    "can-connect-feathers": "^2.0.0",
    "can-define": "^1.0.17",
    "can-route": "^3.0.10",
    "can-route-pushstate": "^3.0.3",
    "can-set": "^1.2.0",
    "can-stache": "^3.0.20",
    "can-view-autorender": "^3.0.4",
    "can-zone": "^0.6.6",
    "documentjs": "^0.5.0",
    "done-autorender": "^1.0.0",
    "done-component": "^1.0.0",
    "done-css": "^3.0.0",
    "done-serve": "^1.0.0",
    "font-awesome": "^4.7.0",
    "generator-donejs": "^1.0.0",
    "steal": "^1.5.4",
    "steal-less": "^1.2.0",
    "steal-platform": "0.0.4",
    "steal-stache": "^3.0.5",
    "testee": "^0.4.0"
  },
  "devDependencies": {
    "can-fixture": "^1.0.13",
    "donejs-cli": "^1.0.0",
    "firebase-tools": "^3.9.0",
    "funcunit": "^3.2.0",
    "steal-qunit": "^1.0.1",
    "steal-tools": "^1.2.0",
    "testee": "^0.3.0"
  }
}
```

**Comment by matthewp** [comment]
Will be fixing here: https://github.com/canjs/can-vdom/issues/22

**Comment by matthewp** [comment]
@nriesco fixed in https://github.com/canjs/can-vdom/releases/tag/v3.2.0 . Will reopen if you are still having problems. Thanks for the awesome bug report!

**Comment by nriesco** [comment]
Thanks @matthewp for such a quick fix. It seems to work now, we'll do more tests during this week but 99% sure it's ok now

**Comment by matthewp** [comment]
Awesome!
