### ISSUE TITLE
The website throws an error related to the donejs survey component

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#1040]
I am experiencing this locally as well.

```
steal.production.js:10 Error: Error loading "bit-docs-site@0.0.1#static" at https://donejs.com/static/static.js
Creating an instance of a named control without passing an element
    at f.setup (static.js:161)
    at Function.newInstance (static.js:77)
    at r (static.js:77)
    at f (static.js:77)
    at e (static.js:423)
    at Function.<anonymous> (static.js:423)
    at execute (steal.production.js:9)
    at m (steal.production.js:9)
    at m (steal.production.js:9)
    at i (steal.production.js:9) "Error: Error loading "bit-docs-site@0.0.1#static" at https://donejs.com/static/static.js
Creating an instance of a named control without passing an element
    at f.setup (https://donejs.com/static/bundles/bit-docs-site/static.js:161:2569)
    at Function.newInstance (https://donejs.com/static/bundles/bit-docs-site/static.js:77:844)
    at r (https://donejs.com/static/bundles/bit-docs-site/static.js:77:1410)
    at f (https://donejs.com/static/bundles/bit-docs-site/static.js:77:1751)
    at e (https://donejs.com/static/bundles/bit-docs-site/static.js:423:97)
    at Function.<anonymous> (https://donejs.com/static/bundles/bit-docs-site/static.js:423:409)
    at execute (https://donejs.com/static/node_modules/steal/steal.production.js:9:12845)
    at m (https://donejs.com/static/node_modules/steal/steal.production.js:9:3966)
    at m (https://donejs.com/static/node_modules/steal/steal.production.js:9:3928)
    at i (https://donejs.com/static/node_modules/steal/steal.production.js:9:2593)"
(anonymous) @ steal.production.js:10
O @ steal.production.js:8
K @ steal.production.js:8
z.when @ steal.production.js:8
v.run @ steal.production.js:8
a._drain @ steal.production.js:8
drain @ steal.production.js:8
b @ steal.production.js:8
characterData (async)
(anonymous) @ steal.production.js:8
a.run @ steal.production.js:8
a.enqueue @ steal.production.js:8
v.become @ steal.production.js:8
v.resolve @ steal.production.js:8
b @ steal.production.js:8
(anonymous) @ steal.production.js:8
d @ steal.production.js:8
f.onreadystatechange @ steal.production.js:8
XMLHttpRequest.send (async)
d @ steal.production.js:8
(anonymous) @ steal.production.js:8
c @ steal.production.js:8
b @ steal.production.js:8
value @ steal.production.js:8
a.fetch @ steal.production.js:9
a.fetch @ steal.production.js:9
a.fetch @ steal.production.js:9
(anonymous) @ steal.production.js:8
O @ steal.production.js:8
K @ steal.production.js:8
y.when @ steal.production.js:8
D.run @ steal.production.js:8
a._drain @ steal.production.js:8
drain @ steal.production.js:8
b @ steal.production.js:8
characterData (async)
(anonymous) @ steal.production.js:8
a.run @ steal.production.js:8
a.enqueue @ steal.production.js:8
w.when @ steal.production.js:8
t.chain @ steal.production.js:8
b.then @ steal.production.js:8
a.normalize @ steal.production.js:9
a.normalize @ steal.production.js:9
a.normalize @ steal.production.js:9
a.normalize @ steal.production.js:9
a.normalize @ steal.production.js:9
a.normalize @ steal.production.js:9
import @ steal.production.js:8
a.import @ steal.production.js:8
u.startup @ steal.production.js:10
(anonymous) @ steal.production.js:10
(anonymous) @ steal.production.js:10
```

**Comment by chasenlehara** [comment]
I think this is the relevant line that’s causing the error:

<img width="515" alt="screen shot 2017-10-23 at 9 31 37 am" src="https://user-images.githubusercontent.com/10070176/31901022-2467527e-b7d5-11e7-9354-8af64ade28ff.png">

It looks like that is causing the control to be called as a function ([here’s where the control is exported](https://github.com/donejs/survey-ad/blob/b4d430ca5e60eb5a5886a3081ab09c4e3c46c496/src/donejs-survey-ad.js#L5)).

**Comment by matthewp** [comment]
@chasenlehara  I have a fix in https://github.com/donejs/survey-ad/pull/2

**Comment by chasenlehara** [comment]
That’s what I get for sequentially responding to my emails. 😂

Thanks for the fix; is this issue breaking anything on the site? If not, I’ll update/release/deploy everything next week when we’re prepping for the second survey.

**Comment by matthewp** [comment]
@chasenlehara Can you do a release to get this fix in? Otherwise can you give me npm permissions on that repo?

**Comment by chasenlehara** [comment]
I think I already released it (but I added you as an owner anyway). https://github.com/donejs/survey-ad/releases/tag/v0.2.0
