### ISSUE TITLE
Verify donejs-chat and place-my-order guides work with donejs@beta

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#1045]
Go through the guides making sure they still work. When prompted use `donejs@beta` instead of `donejs` in the npm install. Everything else should remain the same.

**Comment by Sinjhin** [comment]
# Quick start guide
- [ ] Getting a warning right after app generator runs on first load
```
The module with address http://localhost:8080/node_modules/can-zone/register.js is being instantiated twice.
This happens when module identifiers normalize to different module names.

Modules:
	node_modules/can-zone/register
		 - http://localhost:8080/package.json

	can-zone@0.6.13#register
		 - http://localhost:8080/node_modules/can-zone/lib/zone.js

HINT: Import the module using the ~/[modulePath] identifier.
Learn more at https://stealjs.com/docs/moduleName.html and https://stealjs.com/docs/tilde.html
```

- [x] Getting this warning when switching tabs immediately after adding the tabs in the "Update the Page" section of the quick start
```
can-log.js:105 WARN: "@isActive" is not in the current scope, so it is being read from the parent scope.
This will not happen automatically in an upcoming release. See https://canjs.com/doc/can-stache.scopeAndContext.html#PreventingScopeWalking.
```
- [ ] Getting these warning all the time: 
  - `can-log.js:105 WARN: The helper isProduction has already been registered.`
  - `WARN: Custom tag: chat-messages is already defined`
- [ ] It's really hard to capture it but I am seeing either a weird unstyled homepage or an unstyled list of messages if I go to the homepage and refresh very quickly before the main styles load
- [ ] Got this error when running `donejs build electron`:
```
? What architectures would you like to support? (Press <space> to select, <a> to toggle all, <i> to inverse selection)64-bit (x64)
npm ERR! path /Users/sinjhin/Workspace/donejs-chat/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/sinjhin/Workspace/donejs-chat/node_modules/npm/node_modules/ansicolors' -> '/Users/sinjhin/Workspace/donejs-chat/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sinjhin/.npm/_logs/2017-10-31T18_26_01_991Z-debug.log
npm ERR! path /Users/sinjhin/Workspace/donejs-chat/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/sinjhin/Workspace/donejs-chat/node_modules/npm/node_modules/ansicolors' -> '/Users/sinjhin/Workspace/donejs-chat/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sinjhin/.npm/_logs/2017-10-31T18_26_13_943Z-debug.log
```

**Comment by matthewp** [comment]
The `@isActive` warning is coming from bit-tabs, issue: https://github.com/bitovi-components/bit-tabs/issues/26

Think you can take this one @Sinjhin ?

**Comment by matthewp** [comment]
Electron issue: https://github.com/donejs/donejs-electron/issues/18

**Comment by Sinjhin** [comment]
# In-Depth Guide
- [ ] Getting these warnings
  - `extend ' .clearfix' has no matches`
  - `can-log.js:105 WARN: "state" is not in the current scope, so it is being read from the parent scope.`... Same with `slug`, `statusTitle`, `action`, `emptyMessage`
  - `WARN: can-component: Assigning a DefineMap or constructor type to the viewModel property may not be what you intended. Did you mean ViewModel instead? More info: https://canjs.com/doc/can-component.prototype.ViewModel.html`
  - `WARN: can-util/dom/events::dispatch: Dispatching a synthetic event on a disabled is problematic in FireFox and Internet Explorer. We recommend avoiding this if at all possible. see https://github.com/canjs/can-util/issues/294`
  - `WARN: can-stache/src/expression.js: Unable to find key or helper "restaurant.name".` after updating `src/order/new/new.stache` in "Update the Template" section. Same with `phone`.
- [ ] Warning then errors after copying the whole component `src/order/new/new.js` from the documenting a module section when placing a new order:
<img width="826" alt="screen shot 2017-10-31 at 3 17 25 pm" src="https://user-images.githubusercontent.com/1085104/32246937-aa0199c4-be4e-11e7-8118-3436ad37257f.png">

- [ ] In the Terminal for the DoneJS server I am getting:
  - `WARN: can-view-callbacks: No custom element found for pmo-header` several times
- [ ] In the Terminal for the DoneJS server I am getting:
```
ERROR: Error: The tag 'pmo-loading' has not been properly registered.
    at Object.processImport (file:/Users/sinjhin/Workspace/place-my-order/node_modules/can-view-import/can-view-import.js:49:14)
    at canImport (/Users/sinjhin/Workspace/place-my-order/node_modules/done-ssr/zones/steal/styles/can-import.js:26:16)
    at canImport (/Users/sinjhin/Workspace/place-my-order/node_modules/done-ssr/zones/steal/styles/loaded.js:15:27)
    at file:/Users/sinjhin/Workspace/place-my-order/node_modules/can-observation/can-observation.js:586:17
    at Object.tagHandler (file:/Users/sinjhin/Workspace/place-my-order/node_modules/can-view-callbacks/can-view-callbacks.js:115:41)
    at Element.<anonymous> (file:/Users/sinjhin/Workspace/place-my-order/node_modules/can-stache/can-stache.js:272:21)
    at hydrateCallbacks (file:/Users/sinjhin/Workspace/place-my-order/node_modules/can-view-target/can-view-target.js:256:39)
    at Object.hydrate (file:/Users/sinjhin/Workspace/place-my-order/node_modules/can-view-target/can-view-target.js:275:4)
    at rendererWithScope (file:/Users/sinjhin/Workspace/place-my-order/node_modules/can-stache/src/utils.js:57:11)
    at Object.convertedRenderer (file:/Users/sinjhin/Workspace/place-my-order/node_modules/can-stache/src/utils.js:73:17)
```
- [ ] In the Terminal for the DoneJS server I am getting:
```
ERROR: TypeError: Error loading "place-my-order@0.0.0#home.component!done-component@1.0.0#component" at file:/Users/sinjhin/Workspace/place-my-order/src/home.component
Component.extend is not a function
    at Function.<anonymous> (file:/Users/sinjhin/Workspace/place-my-order/src/home.component:5:39)
    at execute (/Users/sinjhin/Workspace/place-my-order/node_modules/steal/main.js:3244:32)
    at linkDynamicModule (/Users/sinjhin/Workspace/place-my-order/node_modules/steal/main.js:2412:32)
    at link (/Users/sinjhin/Workspace/place-my-order/node_modules/steal/main.js:2271:11)
    at Object.execute (/Users/sinjhin/Workspace/place-my-order/node_modules/steal/main.js:2603:11)
    at doDynamicExecute (/Users/sinjhin/Workspace/place-my-order/node_modules/steal/src/loader/loader.js:1972:25)
    at link (/Users/sinjhin/Workspace/place-my-order/node_modules/steal/src/loader/loader.js:2020:24)
    at doLink (/Users/sinjhin/Workspace/place-my-order/node_modules/steal/src/loader/loader.js:1793:7)
    at updateLinkSetOnLoad (/Users/sinjhin/Workspace/place-my-order/node_modules/steal/src/loader/loader.js:1841:18)
    at /Users/sinjhin/Workspace/place-my-order/node_modules/steal/src/loader/loader.js:1647:11
```
- [ ] When adding `donejs add cordova@1` I get the error **(FIXED BY DELETING node_modules/documentjs)**:
```
Cube-8:place-my-order sinjhin$ donejs add cordova@1
Installing donejs-cordova@1
+ donejs-cordova@1.0.1
added 6 packages and removed 88 packages in 7.937s
? Name of project for Cordova place my order
? ID of project for Cordova com.donejs.placemyorder
? The URL of the service layer 
? What platforms would you like to support (needs SDK installed) (Press <space> to select, <a> to toggle all, <i> to inverse selection)ios
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN can@2.3.8 requires a peer of jquery@>=1.9.0 <3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/async
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/async' -> '/Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/.async.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sinjhin/.npm/_logs/2017-10-31T20_32_06_481Z-debug.log
```
- [ ] When running `donejs add electron@1` I get the error **(FIXED BY DELETING node_modules/documentjs)**:
```
Cube-8:place-my-order sinjhin$ donejs add electron@1
Installing donejs-electron@1
+ donejs-electron@1.0.0
added 6 packages and removed 88 packages in 8.519s
? Main HTML file for your app electron-main.js
? The URL of the service layer http://www.place-my-order.com
? What platforms would you like to support? (Press <space> to select, <a> to toggle all, <i> to inverse selection)MacOS
? What architectures would you like to support? (Press <space> to select, <a> to toggle all, <i> to inverse selection)64-bit (x64)
npm WARN can@2.3.8 requires a peer of jquery@>=1.9.0 <3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/async
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/async' -> '/Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/.async.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sinjhin/.npm/_logs/2017-10-31T20_36_01_345Z-debug.log
npm WARN can@2.3.8 requires a peer of jquery@>=1.9.0 <3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/async
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/async' -> '/Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/.async.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sinjhin/.npm/_logs/2017-10-31T20_36_11_139Z-debug.log
```
- [ ] Same thing with `donejs add firebase@1` **(FIXED BY DELETING node_modules/documentjs)**:
```
Cube-8:place-my-order sinjhin$ donejs add firebase@1
Installing donejs-firebase@1
+ donejs-firebase@1.0.1
added 106 packages, removed 10 packages and updated 6 packages in 15.4s
? What is the Project ID of your Firebase app? place-my-order-sinjhin
Modifying package.json
Finished modifying package.json
    force package.json
   create firebase.json
   create .firebaserc
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN can@2.3.8 requires a peer of jquery@>=1.9.0 <3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/async
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/async' -> '/Users/sinjhin/Workspace/place-my-order/node_modules/documentjs-github-download/node_modules/request/node_modules/form-data/node_modules/.async.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sinjhin/.npm/_logs/2017-10-31T20_39_10_783Z-debug.log
```

**Comment by matthewp** [comment]
@Sinjhin I made that change to donejs-electron and release it, didn't help. I think the issue might be with donejs-cli now, because when it fails, donejs-electron is not installed.

**Comment by matthewp** [comment]
@Sinjhin is testing out a fix. The fix is to remove the `--no-shrinkwrap` flag here: https://github.com/donejs/cli/blob/99110c91b14b823f4b37fdfca30a4695572d2c07/lib/utils.js#L65

**Comment by matthewp** [comment]
These are passing now: https://travis-ci.org/donejs/donejs/jobs/296979454
