### ISSUE TITLE
Help me to integrate feathers 3

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#1056]
I am a bit confused i have in package.json 
 "feathers-client": "https://github.com/feathersjs/client#master",
Could that be the error that this don't get right parsed?

```bash
Error: Error loading "feathers-client@3.0.0#lib" at file:/home/frank/workspace/peep/applications/styleguide/applications/kasse/feathers-client@3.0.0#lib.js
Error loading "feathers-client@3.0.0#lib" from "peep-kasse@0.0.1#index.stache!done-autorender@1.4.0#no-zone" at file:/home/frank/workspace/peep/applications/styleguide/applications/kasse/index.stache
Could not load 'feathers-client@3.0.0#lib'
Is this an npm module not saved in your package.json?
    at file:/home/frank/workspace/peep/applications/styleguide/applications/kasse/node_modules/done-ssr/node_modules/steal/ext/npm-extension.js:366:11
    at /home/frank/workspace/peep/applications/styleguide/applications/kasse/node_modules/can-zone/lib/tasks.js:109:15
    at Task.run (/home/frank/workspace/peep/applications/styleguide/applications/kasse/node_modules/can-zone/lib/zone.js:37:17)
    at Zone.runTask (/home/frank/workspace/peep/applications/styleguide/applications/kasse/node_modules/can-zone/lib/zone.js:178:14)
    at /home/frank/workspace/peep/applications/styleguide/applications/kasse/node_modules/can-zone/lib/zone.js:278:15
    at /home/frank/workspace/peep/applications/styleguide/applications/kasse/node_modules/can-zone/lib/tasks.js:120:21
    at <anonymous>
```

**Comment by matthewp** [comment]
Not sure if this is feathers related... if you point to master like that for *any* module does it work? A steal bug perhaps?

**Comment by frank-dspeed** [comment]
@matthewp oh sorry forgotten that i opened that here it was a feathers bug they did set main wrong i simply don't expected that from them as they are running automated tests and that will in future not depend on the code of them anymore did forks.

**Comment by matthewp** [comment]
Ok, so it sounds like this was resolved, thanks.
