### ISSUE TITLE
After localhost shows, error is produced

### ISSUE THREAD

**Issue by pprogrammingg** [donejs/donejs#1112]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/

__Expected results:__

__Actual results:__

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 
| node -v                  | 
| npm -v                   | 
| Browser                 | 
| Operating system |

**Comment by matthewp** [comment]
Can you provide more information than this please?

**Comment by pprogrammingg** [comment]
Running Node 8.12.0 on Windows 10

Ran:
 >  donejs add app donejs-chat --yes
then
> cd donejs-chat
> donejs devleop

said server is up and checkout localhost:8080. Went there. After about 7-10 seconds of white blank screen, Hello World! appears, then error is thrown. Log below:

file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:261
        return subscription(function _addNodeListener(target, listener) {
               ^

TypeError: subscription is not a function
    at addNodeListener (file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:261:9)
    at Object.<anonymous> (file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:352:32)
    at file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:557:4
    at file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:557:98
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at doEval (/mnt/c/tutorials/donejs-chat/node_modules/steal/main.js:4312:10)
    at __eval (/mnt/c/tutorials/donejs-chat/node_modules/steal/main.js:4416:7)
    at Loader.exec [as __exec] (/mnt/c/tutorials/donejs-chat/node_modules/steal/main.js:2427:5)
    at load.metadata.execute (/mnt/c/tutorials/donejs-chat/node_modules/steal/main.js:3398:13)

file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:261
        return subscription(function _addNodeListener(target, listener) {
               ^

TypeError: subscription is not a function
    at addNodeListener (file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:261:9)
    at Object.<anonymous> (file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:352:32)
    at file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:557:4
    at file:/mnt/c/tutorials/donejs-chat/node_modules/can-dom-mutate/can-dom-mutate.js:557:98
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at doEval (/mnt/c/tutorials/donejs-chat/node_modules/steal/main.js:4312:10)
    at __eval (/mnt/c/tutorials/donejs-chat/node_modules/steal/main.js:4416:7)
    at Loader.exec [as __exec] (/mnt/c/tutorials/donejs-chat/node_modules/steal/main.js:2427:5)
    at load.metadata.execute (/mnt/c/tutorials/donejs-chat/node_modules/steal/main.js:3398:13)
Received client connection

**Comment by pprogrammingg** [comment]
Software | Version
-- | --
donejs -V |  2.1.0
node -v |  8.12.0
npm -v |  6.4.1
Browser |  Updating Google Chrome Version 69.0.3497.81 (Official Build) (64-bit)
Operating system | Windows 10

**Comment by matthewp** [comment]
I just ran it and didn't receive this problem. Any chance you can try again? Wonder if npm was having issues or something at the time you ran it.

**Comment by matthewp** [comment]
Pinging you on this @pprogrammingg  :) If you wouldn't mind retrying again and letting me know it would be appreciated.

**Comment by matthewp** [comment]
Let me know if you are able to do this and I'll reopen.
