### ISSUE TITLE
Error in can-route-pushstate on live-reload

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#1116]
This happens when you live-reload, probably related to teardown.

```
TypeError: Cannot read property 'documentElement' of undefined
	    at PushstateObservable.teardown (file:/Users/matthew/dev/my-new-app/node_modules/can-route-pushstate/can-route-pushstate.js:244:45)
	    at KeyTree.delete (file:/Users/matthew/dev/my-new-app/node_modules/can-key-tree/can-key-tree.js:243:28)
```

**Comment by matthewp** [comment]
This is caused by the fact that done-ssr no longer keeps a global document around always. Probably we should enable this in devMode.
