### ISSUE TITLE
Error with live reload in SSR (document undefined)

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#1157]
Following the guide to this section: https://donejs.com/place-my-order.html#add-data-to-the-page

And updating `list.js` with:

```js
import { Component } from 'can';
import './list.less';
import view from './list.stache';
import Restaurant from '~/models/restaurant';

const RestaurantList = Component.extend({
  tag: 'pmo-restaurant-list',
  view,
  ViewModel: {
    // EXTERNAL STATEFUL PROPERTIES
    // These properties are passed from another component. Example:
    // value: {type: "number"}

    // INTERNAL STATEFUL PROPERTIES
    // These properties are owned by this component.
    restaurants: {
      default() {
        return Restaurant.getList({});
      }
    },

    // DERIVED PROPERTIES
    // These properties combine other property values. Example:
    // get valueAndMessage(){ return this.value + this.message; }

    // METHODS
    // Functions that can be called by the view. Example:
    // incrementValue() { this.value++; }

    // SIDE EFFECTS
    // The following is a good place to perform changes to the DOM
    // or do things that don't fit in to one of the areas above.
    connectedCallback(element){

    }
  }
});

export default RestaurantList;
export const ViewModel = RestaurantList.ViewModel;
```

Breaks in the following way:

```
Live-reload server listening on port 8012
Received client connection
Received client connection
Received client connection
Received client connection
Reloading place-my-order@0.0.0#pages/restaurant/list/list
Custom tag: pmo-restaurant-list is already defined
(node:38963) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getElementsByTagName' of undefined
	    at renderTagsInDocument (file:/Users/justin/dev/place-my-order/node_modules/can-view-callbacks/can-view-callbacks.js:96:34)
	    at Object.tag (file:/Users/justin/dev/place-my-order/node_modules/can-view-callbacks/can-view-callbacks.js:228:5)
	    at Function.setup (file:/Users/justin/dev/place-my-order/node_modules/can-component/can-component.js:336:19)
	    at Function.extend (file:/Users/justin/dev/place-my-order/node_modules/can-construct/can-construct.js:702:29)
	    at execute (file:/Users/justin/dev/place-my-order/src/pages/restaurant/list/list.js!eval:16:34)
	    at doExecute (/Users/justin/dev/place-my-order/node_modules/steal/src/loader/loader.js:935:22)
	    at ensureEvaluated (/Users/justin/dev/place-my-order/node_modules/steal/src/loader/loader.js:1000:11)
	    at doEnsureEvaluated (/Users/justin/dev/place-my-order/node_modules/steal/src/loader/loader.js:963:15)
	    at evaluateLoadedModule (/Users/justin/dev/place-my-order/node_modules/steal/src/loader/loader.js:920:5)
	    at /Users/justin/dev/place-my-order/node_modules/steal/src/loader/loader.js:1140:20
(node:38963) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:38963) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by justinbmeyer** [comment]
I also noticed that if I make changes to the template and then refresh the browser, I get the same error.

**Comment by matthewp** [comment]
This is fixed.

**Comment by matthewp** [comment]
PR: https://github.com/canjs/can-view-callbacks/pull/107
