### ISSUE TITLE
requirePackage is not a function

### ISSUE THREAD

**Issue by cherifGsoul** [donejs/donejs#1162]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
Generating a new app or new plugin throws this error
```
Installing generator-donejs@^3.0.0
+ generator-donejs@3.2.0
added 326 packages in 6.256s
TypeError: require(...).requirePackage is not a function
    at Object.<anonymous> (/Users/cherif_b/public_html/app-ui/node_modules/errlop/index.js:4:38)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cherif_b/public_html/app-ui/node_modules/editions/edition-node-0.8/index.js:12:14)
    at Module._compile (module.js:652:30)
```

__Steps to reproduce:__
```donejs add app myapp``` or ```donejs add plugin myplugin```

__Expected results:__
Install deps and scaffold application or plugin

__Actual results:__
Error:
```TypeError: require(...).requirePackage is not a function```
...
```Command `/Users/cherif_b/public_html/app-ui/node_modules/.bin/donejs` did not complete successfully```

__Environment:__

| Software                             | Version
| -------------------------- | -------
| donejs -V                            | 3.1.0
| npm ls generator-donejs   | 
| node -v                               | v8.11.3
| npm -v                                | 5.6.0
| Operating system              | macOS high sierra 10.13.6

**Comment by matthewp** [comment]
Yeah, I know about this. It's caused by a downstream dependency. Appears to be worked on currently: https://github.com/bevry/errlop/issues/2

**Comment by matthewp** [comment]
This was fixed.
