### ISSUE TITLE
`donejs init` breaks when inside existing node project.

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#207]
I'm putting together an article on using DoneJS with FeathersJS all on one server.  I'm creating a basic structure using what will probably become a very common workflow.
1. `mkdir test-app; cd test-app`
2. `touch server.js`
3. `npm init`
4. `donejs init app-ui`
5. Rename `app-ui` folder to `public`

If I run donejs init BEFORE creating a package.json for the server, there's no problem, but running it while there's an existing package.json produces the following error:

``` console
Bitovi:test-app bitovi$ donejs init test-ui
Creating folder test-ui
Installing generator-donejs
npm WARN package.json test-app@1.0.0 No description
npm WARN package.json test-app@1.0.0 No repository field.
npm WARN package.json test-app@1.0.0 No README data

> spawn-sync@1.0.13 postinstall /Users/bitovi/Sites/test-app/node_modules/generator-donejs/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

generator-donejs@0.3.2 ../node_modules/generator-donejs
├── q@1.4.1
├── lodash@3.10.1
└── yeoman-generator@0.20.3 (detect-conflict@1.0.0, read-chunk@1.0.1, yeoman-welcome@1.0.1, path-is-absolute@1.0.0, path-exists@1.0.0, yeoman-assert@2.1.0, rimraf@2.4.3, async@1.4.2, text-table@0.2.0, mime@1.3.4, class-extend@0.1.2, dargs@4.0.1, istextorbinary@1.0.2, shelljs@0.5.3, user-home@2.0.0, xdg-basedir@2.0.0, debug@2.2.0, run-async@0.1.0, chalk@1.1.1, mkdirp@0.5.1, nopt@3.0.4, cli-table@0.3.1, diff@2.1.3, underscore.string@3.2.2, through2@2.0.0, glob@5.0.15, findup-sync@0.2.1, mem-fs-editor@2.0.4, cross-spawn@2.0.0, github-username@2.0.0, pretty-bytes@2.0.1, dateformat@1.0.11, download@4.2.1, html-wiring@1.2.0, yeoman-environment@1.2.7, gruntfile-editor@1.0.0, sinon@1.17.1, inquirer@0.8.5)
Error: Cannot find module '/Users/bitovi/Sites/test-app/test-ui/node_modules/generator-donejs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/bitovi/npm/lib/node_modules/donejs/lib/utils.js:75:24
    at _fulfilled (/Users/bitovi/npm/lib/node_modules/donejs/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/bitovi/npm/lib/node_modules/donejs/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/bitovi/npm/lib/node_modules/donejs/node_modules/q/q.js:796:13)
    at /Users/bitovi/npm/lib/node_modules/donejs/node_modules/q/q.js:604:44
    at runSingle (/Users/bitovi/npm/lib/node_modules/donejs/node_modules/q/q.js:137:13)
```

The generator detects the current package.json and tries to install `generator-donejs` into the node_modules of the server.  It works correctly as long as I don't first create a package.json for the server app.  If I run `donejs init test-ui` I would expect it to ignore the package.json in the same folder and install the module into `test-ui/node_modules/generator-donejs`.  It doesn't seem like it should matter which order I perform steps 1-5.

**Comment by daffl** [comment]
This should be fixed in the latest release
