### ISSUE TITLE
Getting Started Guide Notes

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#30]
## space before folder name

> Creating folder  place-my-order
> Installing yeoman-environment

**Comment by justinbmeyer** [comment]
# Creating custom elements

I'll be doing this later tonight.

**Comment by justinbmeyer** [comment]
# Setting up routing

## Create Routes

##### from a URL string to properties in our application state

__application view-model__

##### export default AppState; (p0)

`export default AppState;` is listed twice.

**Comment by justinbmeyer** [comment]
# Getting and Displaying Data from the Server

## Creating a restaurants connection.

##### "Creating a restaurants connection." has a period at the end of it. 

We should be consistent everywhere.  Please check.

##### Answer the question about the URL endpoint

We need a better way to show what the answers should be.  Perhaps a screen shot?

**Comment by justinbmeyer** [comment]
# Creating a unit-tested view model

**Comment by justinbmeyer** [comment]
# Setup automated tests and continuous integration (CI)

## Creating a global test page

##### inaccurate title

We don't create this test page.  


##### test.html

Part of me feels this should be in the root folder so I can just go to `localhost/test.html`.

## Using a test runner

##### Color? (p3)

I thought the test output would be reported in color?

## Setting continuous integration (Travis CI)

##### Should we say this is optional?

##### We don't really tell people to create an account, or even post their code to github. (p0)

##### What about other browsers?

Can we show testing them?

**Comment by justinbmeyer** [comment]
## Nested routes

##### Is defaults object necessary?

```
route(':page/:slug', { slug: null });
route(':page/:slug/:action', { slug: null, action: null });
```

**Comment by matthewp** [comment]
Thanks for the feedback. As to live-reload, I believe the problem is [here](https://github.com/donejs/generator-donejs/blob/master/app/index.js#L114).  I don't believe it's possible to run 2 servers with the same command like that.  THe `&` will cause `npm start` to run in the background which we definitely don't want.

**Comment by matthewp** [comment]
Fixed one of the live-reload bug, starting from scratch again to confirm.  https://github.com/donejs/donejs/issues/31

**Comment by matthewp** [comment]
> Adding place-my-order-assets errors: (p0)

cc @justinbmeyer 

Was did you install it in a separate window?  Did the area occur with live-reload running or did this occur when you refreshed the page?

**Comment by matthewp** [comment]
> Now our application is good to go and we can start the server

> It's not really good to go and we had already started it.

What is the suggestion here? Should we tell them to kill the server while installing things?

**Comment by matthewp** [comment]
> home.component (p0)

> donejs generate component home.component pmo-home

should the tag name field be required? If not, what is the default?

**Comment by matthewp** [comment]
## Creating a restaurant list element

> We will learn more about those files and add more functionality to this element in a later chapter but it already contains a fully functional component with a demo page (see localhost:8080/src/restaurant/list/list.html), a basic test (at localhost:8080/src/restaurant/list/test.html) and documentation placeholders.

These links won't work unless you restaurant the server, I guess we should write this note in?)  cc @justinbmeyer

**Comment by matthewp** [comment]
> Switch between components

Just confirming that live-reload did work when updating index.stache while working on this section.

**Comment by matthewp** [comment]
## Test the connection

Just noting that live-reload works through this section.

<img width="699" alt="screen shot 2015-08-10 at 4 35 45 pm" src="https://cloud.githubusercontent.com/assets/361671/9183568/eb8c0174-3f7d-11e5-8b0b-ea056dec9cfe.png">

**Comment by matthewp** [comment]
#### Loading error (p0)

```
My console says:

Not allowed to load local resource: file:///Users/justin/dev/temp/place-my-order/node_modules/place-my-order-assets/images/loading.gif
```

This is because we are using the `~` helper. I think can-ssr should set a default baseURL for the server that can be overridden in the `envs` config (like we do to make cdn work in production).

**Comment by matthewp** [comment]
## Add data to the page

 #### Live-reload is not working (p0)

> When I make these changes, the page does not update.


It works now:

![lrbundle](https://cloud.githubusercontent.com/assets/361671/9188260/502cdf34-3fa8-11e5-8519-0a518037768f.gif)

Also the user should not need to set up `bundle` config for the build, I'll remove that section from the guide when I get there and can confirm.

**Comment by matthewp** [comment]
Live-reload with tests is working now.

**Comment by justinbmeyer** [comment]
# Importing other projects

- [ ] __installing bit-tabs blows up live-reload__ (p0)

<img width="945" alt="cursor_and_place_my_order" src="https://cloud.githubusercontent.com/assets/78602/9217389/aa2bf012-408c-11e5-9409-b02113f2ddce.png">

**Comment by justinbmeyer** [comment]
# Creating data

## Updating the order model

- [ ] __We haven't created an order model yet so this title is strange__ (p3)

- [ ] __using forEach instead of .each__ (p1)

Does forEach live-bind? 

```
total: {
      get() {
        let total = 0.0;
        this.attr('items').forEach(item => total += parseFloat(item.attr('price')));
        return total.toFixed(2);
      }
    }
```

- [ ] __Price should be assigned the "number" type so it doesn't have to be floated here__ (p1)

**Comment by justinbmeyer** [comment]
# Set up a real-time connection

## Adding real-time events to a model

- [ ] __no --save__ (p0)

- [ ] __when npm install is run, we get warnings like:__ (p1)

<img width="790" alt="place_my_order" src="https://cloud.githubusercontent.com/assets/78602/9217852/392e3388-4092-11e5-86ff-7de97c783b45.png">

Do we need to tell them to restart?

**Comment by matthewp** [comment]
live-reload of tests working:

![lrtests](https://cloud.githubusercontent.com/assets/361671/9223507/bdbeb39e-40c8-11e5-84ff-a9d1d8940a58.gif)

**Comment by matthewp** [comment]
#### Adding real-time events to a model

> when npm install is run, we get warnings like: (p1)

This is happening because of live-reload. This project doesn't have a system-config, but can does, so there is a System.configDependencies array in the memory. When it tries to reload "package.json!npm" (which i'm still a little unsure is possible or not) it then wants to load "system-config" which doesn't exist.  I think the temporary solution here is to stop the server at this point.

**Comment by alexisabril** [comment]
<img src="http://content.screencast.com/users/alexis.abril/folders/Jing/media/799e1756-8bd0-445c-8539-ff2cf00f1043/00000190.png"/>

The above section produced the following error. I'm currently investigating, just noting here.

```
helo-3:place-my-order alexisabril$ donejs generate component restaurant/list pmo-restaurant-list
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
    at Object.exports.addImport (/Users/alexisabril/Projects/done-test/place-my-order/node_modules/generator-donejs/lib/utils.js:13:16)
    at module.exports.generators.Base.extend.writing (/Users/alexisabril/Projects/done-test/place-my-order/node_modules/generator-donejs/component/index.js:111:13)
    at /Users/alexisabril/Projects/done-test/place-my-order/node_modules/generator-donejs/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by matthewp** [comment]
I get errors the first time I tried to run documentjs:

```
> place-my-order@0.0.0 document /Users/matthew/Projects/pmo-app
> documentjs

Generating docs at docs

/Users/matthew/Projects/pmo-app/node_modules/documentjs/node_modules/q/q.js:126
                    throw e;
                          ^
Error: ENOENT, open '/Users/matthew/Projects/pmo-app/node_modules/documentjs/site/templates/99914b932bd37a50b983c5e7c90ae93b/layout.mustache'

npm ERR! place-my-order@0.0.0 document: `documentjs`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the place-my-order@0.0.0 document script.
npm ERR! This is most likely a problem with the place-my-order package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     documentjs
npm ERR! You can get their info via:
npm ERR!     npm owner ls place-my-order
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "document"
npm ERR! cwd /Users/matthew/Projects/pmo-app
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/matthew/Projects/pmo-app/npm-debug.log
npm ERR! not ok code 0
Error: Could not run command npm run document
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/donejs/bin/donejs:91:23)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
```

To fix I had to run:

```
rm -rf node_modules/documentjs/site/static/build/99914b932bd37a50b983c5e7c90ae93b
rm -rf node_modules/documentjs/site/templates/99914b932bd37a50b983c5e7c90ae93b
```

and then run again.

**Comment by alexisabril** [comment]
https://github.com/donejs/donejs/blob/master/docs/guide.md#test-the-connection currently returns a connection refused error.

Server trace:

```
Live-reload server listening on port 8012
Received client connection
/Users/alexisabril/Projects/done-test/place-my-order/node_modules/can-ssr/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

**Comment by matthewp** [comment]
@alexisabril did you restart the server when you got that error?

**Comment by alexisabril** [comment]
@matthewp Sure did. There seems to be a catch somewhere that allows the server to stay running(vs EXIT 1), however the page doesn't actually update without stopping/restarting the server. It's left in a broken, but running state after the above error.

**Comment by matthewp** [comment]
It's the way our "donejs develop" runs: https://github.com/donejs/generator-donejs/blob/master/app/index.js#L109  This launches the first command as a background task.  Sometimes killing the server doesn't kill the server task and i'm not sure why that is.

**Comment by daffl** [comment]
The connection refused error happens if you don't have the API running (`donejs api`).

**Comment by daffl** [comment]
Also, @alexisabril's `TypeError: undefined is not a function` error issue should be fixed now in the generator.

**Comment by matthewp** [comment]
shouldn't you do a new donejs release to update the generator version?

**Comment by matthewp** [comment]
found another bug in the generator, will do a release once i fix it

**Comment by alexisabril** [comment]
@daffl "The connection refused error happens if you don't have the API running (donejs api)." - Server is running prior to the error:

```
helo-3:place-my-order alexisabril$ donejs develop

> place-my-order@0.0.0 develop /Users/alexisabril/Projects/done-test/place-my-order
> npm start & npm run live-reload


> place-my-order@0.0.0 live-reload /Users/alexisabril/Projects/done-test/place-my-order
> steal-tools live-reload


> place-my-order@0.0.0 start /Users/alexisabril/Projects/done-test/place-my-order
> can-serve --proxy http://localhost:7070 --port 8080
```

"Also, @alexisabril's TypeError: undefined is not a function error issue should be fixed now in the generator." - Awesome! It sounds like there were some issues with the generator, I'll wait for the next merge and try this section again.

**Comment by alexisabril** [comment]
- [ ] [Building To NW.js](https://github.com/donejs/donejs/blob/master/docs/guide.md#building-to-nwjs) should have a full build.js to be consistent with the rest of the guide
- [ ] Running tests produce an error: http://screencast.com/t/puIrCbO0fllu
- [ ] `donejs test` will fail if Firefox is already open or if not installed
- [ ] Cordova/NW.js references should be linked to those projects
- [ ] _Next, if using pushstate routing, we need to update our routes to use hash-based routing because NW.js runs within the file protocol. If you haven't already installed steal-platform, do so now. Then in src/app.js module add the following condition_ This section is outlines a duplicate step from only one step prior
- [ ] `donejs init` doesn't create the file structure outlined in the guide: http://screencast.com/t/0pN4G5f0xR. Actual file structure has a different test setup(test directory & smoke.html which is unused)
- [ ] documentation section of the guide assumes the initial setup & files don't exist, however the generator creates them
- [ ] re-running donejs document after adding documentation in the guide creates the new docs, but doesn't update index.html with the new links
- [ ] formatting issue in "Building to IOS and Android" http://screencast.com/t/TgXIj5nUa
- [ ] Error will be reported on Cordova build section if an Android emulator doesn't exist. This is a non-issue in terms of completing the guide and would be similar if the IOS emulator didn't exist, however may not be clear to a new developer.
- [ ] App is non-responsive: http://screencast.com/t/EjjOe4sk
