### ISSUE TITLE
donejs init fails with no compatible version of donejs-cli

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#305]
```
Projects git:(master) ✗ donejs init djschat
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "donejs-cli"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: donejs-cli@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.5.0-beta.1","0.5.0-beta.2"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matthew/Projects/djschat/npm-debug.log
Error: Command `npm` did not complete successfully
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/donejs/lib/utils.js:45:23)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

**Comment by matthewp** [comment]
The issue was donejs-cli was in a prerelease, so once it was released as 0.5.0 it started working.
