### ISSUE TITLE
Live-reload SSR broke

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#318]
Somehow I am getting:

```
WARN: Custom tag: message-model is already defined
WARN: Custom tag: chat-messages is already defined
Potentially unhandled rejection [4] TypeError: Object #<Object> has no method 'replace'
    at Object.Scanner.scan (evalmachine.<anonymous>:166:20)
    at new Mustache (evalmachine.<anonymous>:113:33)
    at Mustache (evalmachine.<anonymous>:96:20)
    at Object.can.view.register.renderer (evalmachine.<anonymous>:2308:12)
    at Function.renderFunc [as renderer] (evalmachine.<anonymous>:406:38)
    at Constructor.can.Component.can.Construct.extend.setup (evalmachine.<anonymous>:395:30)
    at Function.can.extend.newInstance (evalmachine.<anonymous>:197:23)
    at Constructor.init (evalmachine.<anonymous>:510:30)
    at new Constructor (eval at <anonymous> (evalmachine.<anonymous>:483:53), <anonymous>:1:52)
    at evalmachine.<anonymous>:85:7
```

everytime I refresh my page.  Noticed right after setting up the real-time connection:

http://donejs.com/Guide.html#section=section_Real_timeconnection

**Comment by justinbmeyer** [comment]
restarting made the problem go away.

**Comment by justinbmeyer** [comment]
output right before:

```
Reloading donejs-chat@0.0.0#messages/messages
WARN: Custom tag: chat-messages is already defined
Received client connection
Received client connection
Reloading package.json!npm
Oops! Error reloading package.json!npm
Reloading donejs-chat@0.0.0#models/message
WARN: Custom tag: message-model is already defined
WARN: Custom tag: chat-messages is already defined
Potentially unhandled rejection [4] TypeError: Object #<Object> has no method 'replace
```

**Comment by justinbmeyer** [comment]
I did run a build at this time.  But I don't think that did anything.

**Comment by justinbmeyer** [comment]
repeated all these steps again and I didn't see this.  Very strange.  Closing, but something to reopen if we see it again.

**Comment by janat08** [comment]
Getting same error after importing: import dropin from 'braintree-web-drop-in'
and then trying to init it in connectedCallback:
```js
    var submitButton = window.document.querySelector('#submit-button');

    dropin.create({
      authorization: "sandbox_4jrfwn28_727hcyfsqznpk94q",
      selector: '#dropin-container'
    }, function (err, dropinInstance) {
      if (err) {
        // Handle any errors that might've occurred when creating Drop-in
        console.error(err);
        return;
      }
      submitButton.addEventListener('click', function () {
        dropinInstance.requestPaymentMethod(function (err, payload) {
          if (err) {
            // Handle errors in requesting payment method
          }

          // Send payload.nonce to your server
        });
      });
    });
```

**Comment by justinbmeyer** [comment]
Can you paste your error?

**Comment by janat08** [comment]
I don't know how I managed to get ``custom tag already registered`` error. This dropin package just breaks stealjs once imported, unless scrip tag is used instead of npm. I also have very brittle build currently with 8012 disconnecting and not hot-module-swapping. https://github.com/donejs/done-serve/issues/113

error:
```
file:C:/Users/janat08/Dev/makpal/node_modules/braintree-web-drop-in/index.js:535
createFromScriptTag(create, typeof document !== 'undefined' && document.querySelector('script[data-braintree-dropin-authorization]')); ^ TypeError: document.querySelector is not a function
    at Object. (file:C:/Users/janat08/Dev/makpal/node_modules/braintree-web-drop-in/index.js:535:73)
    at file:C:/Users/janat08/Dev/makpal/node_modules/braintree-web-drop-in/index.js:546:4
    at file:C:/Users/janat08/Dev/makpal/node_modules/braintree-web-drop-in/index.js:546:98
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at doEval (C:\Users\janat08\Dev\makpal\node_modules\steal\main.js:4306:10)
    at __eval (C:\Users\janat08\Dev\makpal\node_modules\steal\main.js:4410:7)
    at Loader.exec [as __exec] (C:\Users\janat08\Dev\makpal\node_modules\steal\main.js:2427:5)
    at load.metadata.execute (C:\Users\janat08\Dev\makpal\node_modules\steal\main.js:3392:13)
    at linkDynamicModule (C:\Users\janat08\Dev\makpal\node_modules\steal\main.js:2764:32)
```

**Comment by justinbmeyer** [comment]
Don't worry about the `custom tag already registered` warning (it's a warning, not an error).  It will happen with live-reload as it re-defines your components.  

Regarding the `document.querySelectorAll`, you need to make sure that code does not run while SSR is running.  SSR runs against a minimal DOM.  Methods like `document.querySelector` are not supported.  

This part of the bitballs guide shows you how to avoid running code during ssr: https://donejs.com/bitballs.html#turn-off-ssr
