### ISSUE TITLE
Windows DoneJS init errors

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#472]
```
> bufferutil@1.1.0 install C:\Users\Matthew\dev\place-my-order\node_modules\buffer
util
> node-gyp rebuild


C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil>if not defined npm_con
fig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\
..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, pl
ease add the "/m" switch.
  bufferutil.cc
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)': function templ
ate has already been defined [C:\Users\Matthew\dev\place-my-order\node_modules\bu
fferutil\build\bufferutil.vcxproj]
  C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\na
  n.h(256): note: see declaration of '_NanEnsureLocal'
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\build\bufferutil.vcxp
roj]
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(661): error C2039: 'FreeCallback': is not a member of 'node' [C:\Users\Matthew\
dev\place-my-order\node_modules\bufferutil\build\bufferutil.vcxproj]
  C:\Users\Matthew\.node-gyp\5.3.0\include\node\node_object_wrap.h(8): note: see
  declaration of 'node'
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(661): error C2061: syntax error: identifier 'FreeCallback' [C:\Users\Matthew\de
v\place-my-order\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(665): error C2065: 'callback': undeclared identifier [C:\Users\Matthew\dev\plac
e-my-order\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(665): error C2065: 'hint': undeclared identifier [C:\Users\Matthew\dev\place-my
-order\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(672): error C2665: 'node::Buffer::New': none of the 4 overloads could convert a
ll the argument types [C:\Users\Matthew\dev\place-my-order\node_modules\bufferuti
l\build\bufferutil.vcxproj]
  C:\Users\Matthew\.node-gyp\5.3.0\include\node\node_buffer.h(43): note: could be
   'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
  C:\Users\Matthew\.node-gyp\5.3.0\include\node\node_buffer.h(31): note: or
   'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::Stri
  ng>,node::encoding)'
  C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\na
  n.h(672): note: while trying to match the argument list '(v8::Isolate *, const
  char *, uint32_t)'
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(676): error C2440: 'return': cannot convert from 'v8::MaybeLocal<v8::Object>' t
o 'v8::Local<v8::Object>' [C:\Users\Matthew\dev\place-my-order\node_modules\buffe
rutil\build\bufferutil.vcxproj]
  C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\na
  n.h(676): note: No constructor could take the source type, or constructor overl
  oad resolution was ambiguous
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(683): error C2039: 'Use': is not a member of 'node::Buffer' [C:\Users\Matthew\d
ev\place-my-order\node_modules\bufferutil\build\bufferutil.vcxproj]
  C:\Users\Matthew\.node-gyp\5.3.0\include\node\node_buffer.h(8): note: see decla
  ration of 'node::Buffer'
C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil\node_modules\nan\nan.
h(683): error C3861: 'Use': identifier not found [C:\Users\Matthew\dev\place-my-o
rder\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed
 with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.
js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\
\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Matthew\dev\place-my-order\node_modules\bufferutil
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by matthewp** [comment]
DocumentJS 0.3.3 was using an older version of steal-tools which used an older version of ws, which I think is the cause of these errors. Upgrading documentjs with https://github.com/donejs/cli/pull/30 might fix it.

**Comment by matthewp** [comment]
This is fixed.
