### ISSUE TITLE
Run server throws error for undefined version

### ISSUE THREAD

**Issue by minsooshin** [donejs/donejs#659]
I have created app with `donejs add app anniv`.
and changed port to avoid conflicts with another app I run.
and run application with `donejs develop`

``` sh
> anniv@0.0.0 develop /Users/mshin/Workspace/github/anniv
> done-serve --develop --port 7000

done-serve starting on http://localhost:7000
Potentially unhandled rejection [8] TypeError: Error loading "anniv@0.0.0#index.stache!done-autorender@0.8.0#autorender" at <unknown>
Error loading "can@2.3.23#util/vdom/document/document" at file:/Users/mshin/Workspace/github/anniv/node_modules/can/util/vdom/document/document.js
Error loading "can@2.3.23#util/vdom/document/document" from "done-autorender@0.8.0#autorender" at file:/Users/mshin/Workspace/github/anniv/node_modules/done-autorender/src/autorender.js
Cannot read property 'version' of undefined
    at createModuleNameAndNormalize (file:/Users/mshin/Workspace/github/anniv/node_modules/steal/ext/npm-extension.js:179:37)
    at tryCatchReject (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1142:4)
    at Fulfilled.when (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:930:4)
    at Pending.run (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:821:13)
    at Scheduler._drain (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:97:19)
    at Scheduler.drain (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:62:9)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
Potentially unhandled rejection [7] TypeError: Error loading "can@2.3.23#util/vdom/document/document" at file:/Users/mshin/Workspace/github/anniv/node_modules/can/util/vdom/document/document.js
Error loading "can@2.3.23#util/vdom/document/document" from "anniv@0.0.0#index.stache!done-autorender@0.8.0#autorender" at file:/Users/mshin/Workspace/github/anniv/src/index.stache
Cannot read property 'version' of undefined
    at createModuleNameAndNormalize (file:/Users/mshin/Workspace/github/anniv/node_modules/steal/ext/npm-extension.js:179:37)
    at tryCatchReject (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1142:4)
    at Fulfilled.when (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:930:4)
    at Pending.run (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:821:13)
    at Scheduler._drain (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:97:19)
    at Scheduler.drain (/Users/mshin/Workspace/github/anniv/node_modules/steal/node_modules/steal-systemjs/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:62:9)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
```

**Comment by matthewp** [comment]
Trying to recreate now.

**Comment by matthewp** [comment]
Not able to recreate, you sure there's not something else running on that port? Or is there a node process that is hanging? On Linux/Mac you can do `ps aux | grep node` to see if there are node processes.

**Comment by minsooshin** [comment]
@matthewp there are some node processes are going on for Atom IDE.

**Comment by minsooshin** [comment]
@matthewp I found there is a running node process from another application. BTW, I cannot run `done-server` if I am running other node application? Still, I am having same error log even with stopping another node application.

**Comment by minsooshin** [comment]
@matthewp I am sorry, but I don't know why. I have tried with other app name: `anniversary` and `example`, and it works without any issue. `anniv` app name has issue. I think this is not as issue any more.

**Comment by minsooshin** [comment]
@matthewp I am sorry. This is not a bug. I made a mistake while I am generating the app with `donejs add app <appname>`. I put 4 for `NPM version used` question. I misunderstood it is `node version`. After I go with default value (2), no issue any more.

**Comment by minsooshin** [comment]
I will close this issue since this is because of my mistake in generating process.

**Comment by matthewp** [comment]
Hey @minsooshin, glad you figured it out. I'm going to try and recreate this step and see what happens, maybe we can do better error reporting when this occurs, at the least.

**Comment by matthewp** [comment]
Just so you know, we pre-populate that field with the version of npm you are currently using, usually you can just click enter to that question.
