### ISSUE TITLE
Errors occur when app is built using Cordova

### ISSUE THREAD

**Issue by shubhamgupta28** [donejs/donejs#664]
# Environment:

MacOS X El Capitan
Chrome  50.0

Steps:
I have added Cordova according to the in-depth guide of place-my-order, inside my app, but still, while building the app using Cordova, several errors show up : 

Here are the errors: 
```
Creating a new cordova project.
Done-> cordova create ./build/cordova com.elated.mobile @acme/mobile
Running:/Users/Shubham/Sites/@acme/mobile/node_modules/cordova/bin/cordova platform add ios
Adding ios project...
Running command: /Users/Shubham/.cordova/lib/npm_cache/cordova-ios/3.9.2/package/bin/create /Users/Shubham/Sites/@acme/mobile/build/cordova/platforms/ios com.elated.mobile @acme/mobile --cli
shell.js: internal error
Error: ENOENT: no such file or directory, rename '/Users/Shubham/Sites/@acme/mobile/build/cordova/platforms/ios/__CLI__.xcodeproj' -> '/Users/Shubham/Sites/@acme/mobile/build/cordova/platforms/ios/@acme/mobile.xcodeproj'
    at Error (native)
    at Object.fs.renameSync (fs.js:803:18)
    at /Users/Shubham/.cordova/lib/npm_cache/cordova-ios/3.9.2/package/bin/node_modules/shelljs/shell.js:495:8
    at Array.forEach (native)
    at Object._mv (/Users/Shubham/.cordova/lib/npm_cache/cordova-ios/3.9.2/package/bin/node_modules/shelljs/shell.js:471:11)
    at Object.mv (/Users/Shubham/.cordova/lib/npm_cache/cordova-ios/3.9.2/package/bin/node_modules/shelljs/shell.js:1491:23)
    at Object.exports.createProject (/Users/Shubham/.cordova/lib/npm_cache/cordova-ios/3.9.2/package/bin/lib/create.js:168:15)
    at Object.<anonymous> (/Users/Shubham/.cordova/lib/npm_cache/cordova-ios/3.9.2/package/bin/create:53:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
Error: /Users/Shubham/.cordova/lib/npm_cache/cordova-ios/3.9.2/package/bin/create: Command failed with exit code 1
Done-> cordova platform add ios
Error-> with Parallel tasks1
Running:/Users/Shubham/Sites/@acme/mobile/node_modules/cordova/bin/cordova plugin add cordova-plugin-transport-security
(node:20350) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Fetching plugin "cordova-plugin-transport-security" via npm
Installing "cordova-plugin-transport-security" for ios
Failed to install 'cordova-plugin-transport-security':CordovaError: could not find -Info.plist file, or config.xml file.
    at Object.module.exports.parseProjectFile (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/src/plugman/platforms/ios.js:271:19)
    at PlatformApiPoly.addPlugin (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:246:71)
    at handleInstall (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/src/plugman/install.js:603:6)
    at /Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/src/plugman/install.js:382:28
    at _fulfilled (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:509:49
    at flush (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
Error: could not find -Info.plist file, or config.xml file.
Done-> cordova plugin add cordova-plugin-transport-security
Error-> with Series tasks1
Success-> with Series tasks
Using cordova CLI version (5.4.1) 
Running:/Users/Shubham/Sites/@acme/mobile/node_modules/cordova/bin/cordova build --release
(node:20351) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
shell.js: internal error
TypeError: Cannot use 'in' operator to search for 'length' in undefined
    at Object._cp (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/shelljs/src/cp.js:122:26)
    at Object.cp (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at PlatformApiPoly.prepare (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:192:15)
    at /Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/src/cordova/prepare.js:100:32
    at _fulfilled (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:810:14
    at flush (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
Done-> cordova build --release
Error-> with Series tasks1
Using cordova CLI version (5.4.1) 
Setting Current Working Directory (CWD) to ./build/cordova
Running:/Users/Shubham/Sites/@acme/mobile/node_modules/cordova/bin/cordova emulate ios
(node:20352) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
shell.js: internal error
TypeError: Cannot use 'in' operator to search for 'length' in undefined
    at Object._cp (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/shelljs/src/cp.js:122:26)
    at Object.cp (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at PlatformApiPoly.prepare (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:192:15)
    at /Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/src/cordova/prepare.js:100:32
    at _fulfilled (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:810:14
    at flush (/Users/Shubham/Sites/@acme/mobile/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
Done-> cordova emulate ios
Error-> with Parallel tasks1
```

Please help!

**Comment by matthewp** [comment]
Sorry for getting back to you so late, what version of Node are you using?
