### ISSUE TITLE
can-serve dies when place-my-order-api isn't running on page load

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#68]
_Issue by **[marshallswain](https://github.com/marshallswain)** from Thursday Aug 20, 2015 at 18:59 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/49_

---

Server has to be restarted.

![screen shot 2015-08-20 at 1 55 29 pm 1](https://cloud.githubusercontent.com/assets/128857/9392635/7ef415ce-4743-11e5-95d5-9354ea6a3747.png)

Text version:

```
/Users/bitovi/Sites/place-my-order/node_modules/can-ssr/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! place-my-order@0.0.0 start: `can-serve --port 8080 --proxy http://localhost:7070`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the place-my-order@0.0.0 start script 'can-serve --port 8080 --proxy http://localhost:7070'.
npm ERR! This is most likely a problem with the place-my-order package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     can-serve --port 8080 --proxy http://localhost:7070
npm ERR! You can get their info via:
npm ERR!     npm owner ls place-my-order
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bitovi/Sites/place-my-order/npm-debug.log
```

**Comment by daffl** [comment]
This should probably throw a better error message when proxying in https://github.com/canjs/can-ssr/blob/master/lib/server/proxy.js#L3.

**Comment by daffl** [comment]
I think this should be fixed in the new done-ssr
