### ISSUE TITLE
Prerelease: v0.10.0-pre.1 live reload breaks on package.json changes.

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#696]
In a freshly generated app, whenever I make any change to the package.json, whether directly or by installing a module, it gives the following error in the browser and donejs develop console.  The server has to be restarted to continue development.

```
TypeError: Cannot read property 'route' of undefined
   at /Users/marshall/Sites/mma-test/node_modules/done-ssr/lib/make_render.js:37:26
   at /Users/marshall/Sites/mma-test/node_modules/done-ssr/lib/make_render.js:10:16
   at /Users/marshall/Sites/mma-test/node_modules/done-ssr/lib/index.js:120:5
   at Task.run (/Users/marshall/Sites/mma-test/node_modules/can-zone/lib/zone.js:37:17)
   at Zone.run (/Users/marshall/Sites/mma-test/node_modules/can-zone/lib/zone.js:196:26)
   at /Users/marshall/Sites/mma-test/node_modules/done-ssr/lib/index.js:118:16
   at tryCatchReject (/Users/marshall/Sites/mma-test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1183:30)
   at runContinuation1 (/Users/marshall/Sites/mma-test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1142:4)
   at Fulfilled.when (/Users/marshall/Sites/mma-test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:930:4)
   at ContinuationTask.run (/Users/marshall/Sites/mma-test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1040:24)
```

**Comment by matthewp** [comment]
If you replace this line: https://github.com/donejs/done-ssr/blob/can3/lib/startup.js#L46  instead of `"@ssr"` you do `loader.main` does that fix it?

**Comment by marshallswain** [comment]
Nope.  It doesn't make any difference.

**Comment by marshallswain** [comment]
I tried updating packages to see if it made any difference.  This is my current setup:

```
"dependencies": {
    "can-component": "^3.0.0-pre.14",
    "can-define": "^0.7.17",
    "can-route": "^3.0.0-pre.13",
    "can-route-pushstate": "^3.0.0-pre.3",
    "can-stache": "^3.0.0-pre.6",
    "can-view-autorender": "^3.0.0-pre.3",
    "can-zone": "^0.5.7",
    "canjs-feathers": "^1.0.0-pre.0",
    "done-autorender": "^0.9.0-pre.0",
    "done-component": "^0.6.0-pre.1",
    "done-css": "~2.1.0-pre.0",
    "done-serve": "^0.3.0-pre.0",
    "engine.io-client": "^1.6.11",
    "feathers": "^2.0.1",
    "feathers-authentication": "^0.7.9",
    "feathers-hooks": "^1.5.5",
    "feathers-rest": "^1.4.3",
    "feathers-socketio": "^1.4.1",
    "generator-donejs": "^0.10.0-pre.0",
    "jquery": "^3.1.0",
    "socket.io-client": "^1.4.8",
    "socket.io-parser": "^2.2.6",
    "steal": "^0.16.35",
    "steal-stache": "^3.0.0-pre.2"
  },
  "devDependencies": {
    "can-fixture": "^0.4.0-pre.2",
    "documentjs": "^0.4.2",
    "donejs-cli": "^0.10.0-pre.0",
    "donejs-deploy": "^0.4.0",
    "funcunit": "~3.0.0",
    "jshint": "^2.9.2",
    "steal-qunit": "^0.1.1",
    "steal-tools": "^0.16.6",
    "testee": "^0.2.4"
  }
```

**Comment by matthewp** [comment]
I couldn't recreate with those dependencies. It must be related to how you are using them. Can you reduce it down, by removing imports until the problem goes away, to isolate which one causes the issue? I would start by removing all of your can-imports in your index.stache.
