### ISSUE TITLE
DoneJS prerelease: using setVal with promises is broken.

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#697]
I'm not sure where to file this.  Returning a promise from a getter is throwing the error below.  The ViewModel looks like this.  I'm using Promise.resolve to eliminate the Model as the possible cause of the error:

``` js
import Component from 'can-component';
import DefineMap from 'can-define/map/';
import './account-list.less';
import template from './account-list.stache';
import Account from 'mma-test/models/account';

export const ViewModel = DefineMap.extend({
  accounts: {
    get(val, setVal){
      return Promise.resolve(new Account.List([
        {name: 'Checking'},
        {name: 'Savings'},
      ])).then(setVal);
    }
  }
});
```

This template results in the error.  It probably has something with trying to iterate over a promise with #each.  (We should probably make it fail more gracefully when somebody tries to iterate over a promise.):

``` html
<ul>
  {{#each accounts}}
    <li>
      <span>{{name}}</span>
    </li>
  {{/each}}
</ul>
```

If I change the template to better handle the promise, the inner section never gets rendered, and the {{log}} never happens.

``` html
{{#if accounts.isResolved}}
  {{log}}
  <ul>
    {{#each accounts}}
      <li>
        <span>{{name}}</span>
      </li>
    {{/each}}
  </ul>
{{/if}}
```

Here's the stack trace of the error I get with the first template.

```
steal.js:140 Potentially unhandled rejection [5] TypeError: Cannot read property 'join' of undefined
    at Promise.then (http://localhost:8080/node_modules/steal/steal.js:471:22)
    at http://localhost:8080/node_modules/can-zone/lib/tasks.js:125:15
    at wrappedFn (http://localhost:8080/node_modules/can-zone/register.js:89:37)
    at promiseThen (http://localhost:8080/node_modules/can-zone/lib/zones/globals.js:84:26)
    at http://localhost:8080/node_modules/can-zone/lib/tasks.js:125:15
    at promiseThen (http://localhost:8080/node_modules/can-zone/lib/zones/globals.js:86:42)
    at Object.read (http://localhost:8080/node_modules/can-observation/reader/reader.js:150:18)
    at readValue (http://localhost:8080/node_modules/can-observation/reader/reader.js:24:43)
    at Object.read (http://localhost:8080/node_modules/can-observation/reader/reader.js:72:13)
    at Scope._read (http://localhost:8080/node_modules/can-view-scope/can-view-scope.js:208:30)(anonymous function) 
    @ steal.js:140report 
    @ steal.js:167flush 
    @ steal.js:189setTimeout (async)wrappedFn 
    @ register.js:92setTimer 
    @ steal.js:224enqueue 
    @ steal.js:182Promise.onPotentiallyUnhandledRejection 
    @ steal.js:149ReportTask.run 
    @ steal.js:993Scheduler._drain 
    @ steal.js:105Scheduler.drain 
    @ steal.js:62run 
    @ steal.js:268characterData (async)(anonymous function) 
    @ steal.js:274Scheduler.run 
    @ steal.js:87Scheduler.enqueue 
    @ steal.js:72Pending.become 
    @ steal.js:833Pending.resolve 
    @ steal.js:786promiseResolve 
    @ steal.js:390(anonymous function) 
    @ steal.js:2824load 
    @ steal.js:2626xhr.onreadystatechange 
    @ steal.js:2635XMLHttpRequest.send (async)wrappedFn 
    @ register.js:92fetchTextFromURL 
    @ steal.js:2648(anonymous function) 
    @ steal.js:2823init 
    @ steal.js:377Promise 
    @ steal.js:365value 
    @ steal.js:2822loader.fetch 
    @ steal.js:3637loader.fetch 
    @ steal.js:4705loader.fetch 
    @ steal.js:4805System.fetch 
    @ npm-extension.js:274(anonymous function) 
    @ steal.js:1525tryCatchReject 
    @ steal.js:1183runContinuation1 
    @ steal.js:1142Fulfilled.when 
    @ steal.js:930Pending.run 
    @ steal.js:821Scheduler._drain 
    @ steal.js:97Scheduler.drain 
    @ steal.js:62run 
    @ steal.js:268characterData (async)(anonymous function) 
    @ steal.js:274Scheduler.run 
    @ steal.js:87Scheduler.enqueue 
    @ steal.js:72Pending.become 
    @ steal.js:833Pending.resolve 
    @ steal.js:786promiseResolve 
    @ steal.js:390(anonymous function) 
    @ steal.js:2824load 
    @ steal.js:2626xhr.onreadystatechange 
    @ steal.js:2635
```

**Comment by marshallswain** [comment]
This is a VM/template combination that renders the data properly:

``` js
accountsPromise: {
    get(){
      return Account.findAll({}).then(response => {
        console.log(response.data);
        this.accounts = response.data;
        return response.data;
      });
    }
  },
```

And this in the template:

``` html
{{#if accountsPromise.isResolved}}
  {{log}}
  <ul>
    {{#each accountsPromise.value}}
      <li>
        <span>{{name}}</span>
      </li>
    {{/each}}
  </ul>
{{/if}}
```

But for some reason, using `setVal` won't render the data.

**Comment by marshallswain** [comment]
I've updated modules, so here's my current set of dependencies:

``` js
"dependencies": {
    "can-component": "^3.0.0-pre.14",
    "can-define": "^0.7.17",
    "can-route": "^3.0.0-pre.13",
    "can-route-pushstate": "^3.0.0-pre.3",
    "can-stache": "^3.0.0-pre.6",
    "can-view-autorender": "^3.0.0-pre.3",
    "can-zone": "^0.5.7",
    "canjs-feathers": "^1.0.0-pre.0",
    "done-autorender": "^0.9.0-pre.0",
    "done-component": "^0.6.0-pre.1",
    "done-css": "~2.1.0-pre.0",
    "done-serve": "^0.3.0-pre.0",
    "engine.io-client": "^1.6.11",
    "feathers": "^2.0.1",
    "feathers-authentication": "^0.7.9",
    "feathers-hooks": "^1.5.5",
    "feathers-rest": "^1.4.3",
    "feathers-socketio": "^1.4.1",
    "generator-donejs": "^0.10.0-pre.0",
    "jquery": "^3.1.0",
    "socket.io-client": "^1.4.8",
    "socket.io-parser": "^2.2.6",
    "steal": "^0.16.35",
    "steal-stache": "^3.0.0-pre.2"
  },
  "devDependencies": {
    "can-fixture": "^0.4.0-pre.2",
    "documentjs": "^0.4.2",
    "donejs-cli": "^0.10.0-pre.0",
    "donejs-deploy": "^0.4.0",
    "funcunit": "~3.0.0",
    "jshint": "^2.9.2",
    "steal-qunit": "^0.1.1",
    "steal-tools": "^0.16.6",
    "testee": "^0.2.4"
  }
```

**Comment by marshallswain** [comment]
The first thing I thought when I woke up this morning was "Oh, I'm an idiot.  I'm probably returning the promise."  It turned out to be true, but removing the `return` before the promise didn't fix it, but it did send it into an infinite loop.  And I see the request for /accounts getting made over and over again.

**Comment by marshallswain** [comment]
this.observation.get() is always undefined or an empty array, here: https://github.com/canjs/can-compute/blob/bbae2aad1f667cca9a9931ec4f9bf17e60b24d22/proto-compute.js#L365

**Comment by justinbmeyer** [comment]
This would almost certainly be a CanJS error.  Anyway you can create a test in can-stache?  There's a define-map test in stache.  I'm closing for an issue there.  

It's odd for a property value to be a promise, and then when `setVal` is called, be something else.
