### ISSUE TITLE
Possible issue when switching branches

### ISSUE THREAD

**Issue by nriesco** [donejs/donejs#730]
Possible issue when switching branches

It seems that switching branches from a project somehow causes some sort of inconsistency.
It is hard to tell exactly what happened but this sequence could help:

```
donejs develop => fail

donejs build
donejs deploy
NODE_ENV=production npm start => FAIL-SEE-DETAILS-BELOW

npm install
donejs develop => fail

donejs build
donejs develop => ok

donejs deploy
NODE_ENV=production npm start => FAIL-SEE-DETAILS-BELOW

npm install
donejs build
donejs deploy
NODE_ENV=production npm start => FAIL-SEE-DETAILS-BELOW

rm -rf node_modules && npm cache clean && npm install
donejs build
donejs develop => OK
NODE_ENV=production npm start => FAIL-SEE-DETAILS-BELOW

rm -rf node_modules && npm cache clean && npm install
donejs build
NODE_ENV=production npm start => FAIL-SEE-DETAILS-BELOW

npm install
donejs build
donejs deploy
NODE_ENV=production npm start => FAIL-SEE-DETAILS-BELOW

npm install
donejs build
NODE_ENV=production npm start =====> FINALLY, it works!!! >> BUT: assets don't
donejs deploy
NODE_ENV=production npm start =====> it works!!! with assets
```

As you might notice there is a strange pattern somehow related to production environment and switching branches. Development mode works sometimes but gets fixed easily.

Facts:

```
node --version
v4.6.2
donejs --version
0.9.2
npm --version
2.15.11
```

------ SOME EXAMPLES -----
PROMPT: `Gris:basic-4 nriesco$`
PROJECT PATH: `/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4`

---- FAIL DETAILS: ----
```
Gris:basic-4 nriesco$ NODE_ENV=production npm start

> basic-4@0.0.0 start /Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4
> done-serve --port 8080

done-serve starting on http://localhost:8080
Potentially unhandled rejection [5] TypeError: Error loading "package.json!npm" at file:/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/package.json
Error loading "bundles/basic-4/index" at file:/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/dist/bundles/basic-4/index.js
Error evaluating file:/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/dist/bundles/basic-4/index.js
define is not a function
    at file:/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/dist/bundles/basic-4/index.js:7:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at doEval (/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/node_modules/steal/node_modules/steal-systemjs/dist/system.src.js:2059:10)
    at __eval (/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/node_modules/steal/node_modules/steal-systemjs/dist/system.src.js:1976:7)
    at Loader.exec [as __exec] (/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/node_modules/steal/node_modules/steal-systemjs/dist/system.src.js:339:5)
    at Loader.loader.instantiate (/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/node_modules/steal/node_modules/steal-systemjs/dist/system.src.js:799:14)
    at Loader.loader.instantiate (/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/node_modules/steal/node_modules/steal-systemjs/dist/system.src.js:1113:30)
    at Loader.loader.instantiate (/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/node_modules/steal/node_modules/steal-systemjs/dist/system.src.js:1225:30)
    at Loader.loader.instantiate (/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/node_modules/steal/node_modules/steal-systemjs/dist/system.src.js:1531:30)
    at Loader.loader.instantiate (/Users/nriesco/git/riescorp/osbhub-donejs-3-demo-1/basic-4/node_modules/steal/node_modules/steal-systemjs/dist/system.src.js:1843:32)
```

**Comment by matthewp** [comment]
What do you mean by branches? Git branches?

**Comment by nriesco** [comment]
I meant when switching from one branch to another: `git checkout master` => `git checkout testing`

**Comment by matthewp** [comment]
So when you switch branches and try to run it (without building) you get problems? It is possible your `dist/` folder is being committed and when you switch branches you get an older/wrong dist folder?

**Comment by nriesco** [comment]
I have the standard/default gitignore file:

```
# DoneJS
docs/
build/
dist/
cache/
```

but I even tried deleting dist, cache and build directories and would help running `donejs develop`
