### ISSUE TITLE
Intermittent live-reload error message

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#790]
This has happened to be a few times, usually when making a mistake like installing the wrong version of bit-tabs, but it's worth investigating further.

```
TypeError: Cannot read property 'route' of undefined
   at /Users/matthew/Projects/djs-chat/node_modules/done-ssr/lib/make_render.js:37:26
   at /Users/matthew/Projects/djs-chat/node_modules/done-ssr/lib/make_render.js:10:16
   at /Users/matthew/Projects/djs-chat/node_modules/done-ssr/lib/index.js:120:5
   at Task.run (/Users/matthew/Projects/djs-chat/node_modules/can-zone/lib/zone.js:37:17)
   at Zone.run (/Users/matthew/Projects/djs-chat/node_modules/can-zone/lib/zone.js:197:26)
   at /Users/matthew/Projects/djs-chat/node_modules/done-ssr/lib/index.js:118:16
   at tryCatchReject (/Users/matthew/Projects/djs-chat/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1183:30)
   at runContinuation1 (/Users/matthew/Projects/djs-chat/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1142:4)
   at Fulfilled.when (/Users/matthew/Projects/djs-chat/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:930:4)
   at ContinuationTask.run (/Users/matthew/Projects/djs-chat/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1040:24)
```

**Comment by matthewp** [comment]
I'm going to try and get to the bottom of this.

**Comment by frank-dspeed** [comment]
@matthewp good luck if you wan't to go even more far you will get conclusion that live-reload aka ssr is broken totally when editing bigger applications it will brake and you need to restart donejs develop all times because when your coding sometimes things brake if you don't paste in pre tested code ;)

**Comment by matthewp** [comment]
@frank-dspeed That sort of comment is not constructive. The best way to get bugs fixed is to provide detailed and reproducible issues. Saying something is "broken totally" doesn't help get anything fixed.

**Comment by frank-dspeed** [comment]
@matthewp i don't think that it is really fixable that a application brakes when there gets some invalid code loaded 

else i would investigate my self but i think its broken by design you cant simply edit every JS object there happen a lot of errors when you replace routes and when you replace other stuff it depends on the used libs also
