### ISSUE TITLE
Adding properties to the Application ViewModel causes live-reload errors

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#869]
```
Potentially unhandled rejection [3] TypeError: Cannot define property:page, object is not extensible.
    at Function.defineProperty (<anonymous>)
    at Function.define.property (http://localhost:8080/node_modules/can-define/can-define.js:223:9)
    at Object.defineExpando (http://localhost:8080/node_modules/can-define/define-helpers/define-helpers.js:43:20)
    at DefineMap.set (http://localhost:8080/node_modules/can-define/map/map.js:200:37)
    at DefineMap.setProps (http://localhost:8080/node_modules/can-define/map/map.js:80:18)
    at DefineMap.set (http://localhost:8080/node_modules/can-define/map/map.js:198:29)
    at DefineMap.attrHelper (http://localhost:8080/node_modules/can-route/can-route.js:91:9)
    at Function.canRoute.attr (http://localhost:8080/node_modules/can-route/can-route.js:936:20)
    at Function.canRoute.setState (http://localhost:8080/node_modules/can-route/can-route.js:332:12)
    at Function.ready (http://localhost:8080/node_modules/can-route/can-route.js:608:14)
```

**Comment by matthewp** [comment]
I wasn't able to recreate this a second time.
